### ISSUE TITLE
Error please help!

### ISSUE THREAD

**Issue by blakefmc** [Fabricio20/HubBasics#52] opened 2016-07-06 06:38 UTC
Hey, I need some help with this error, I'm not sure if its just me or the plugin it self.
Here is the error
```
[18:36:32 INFO]: [HubBasics] Enabling HubBasics v5.0
[18:36:32 ERROR]: Error occurred while enabling HubBasics v5.0 (Is it up to date?)
java.lang.NullPointerException
        at net.notfab.hubbasics.commands.HologramsCmd.<init>(HologramsCmd.java:26) ~[?:?]
        at net.notfab.hubbasics.managers.CommandManager.<init>(CommandManager.java:34) ~[?:?]
        at net.notfab.hubbasics.HubBasics.onEnable(HubBasics.java:49) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]```

**Comment by Fabricio20** [comment] 2016-07-06 09:32
This is a duplicate of #47 which was fixed on 5111077d6186d6b0aa2d4aa5a7ee0dafff95cbc9.

Any builds above 36 on Jenkins have this issue fixed.

**Comment by blakefmc** [comment] 2016-07-06 19:12
I have the latest build it still does not work

**Comment by blakefmc** [comment] 2016-07-06 20:19
I downloaded the latest build of buildtools and extracted spigot 1.8.8 the build tools ver is 52 I think

**Comment by Fabricio20** [comment] 2016-07-06 22:14
Issue reopened, pending check.

**Comment by Fabricio20** [comment] 2016-07-06 23:23
Just tested on build 40, didn't get this error.

```
[20:22:26 INFO]: [HubBasics] Enabling HubBasics v5.0-DEVELOPMENT
[20:22:26 INFO]: HubBasics Debug >> [ModuleManager] COMMAND_OVERRIDE Enabled
[20:22:26 INFO]: HubBasics Debug >> Registered command override for command "plugin".
[20:22:26 INFO]: HubBasics Debug >> [ModuleManager] KEEP_HEALTH Enabled
[20:22:26 INFO]: HubBasics Debug >> [ModuleManager] KEEP_FOOD Enabled
[20:22:26 INFO]: HubBasics Debug >> [ModuleManager] HOLOGRAMS Enabled
[20:22:26 INFO]: HubBasics Debug >> [ModuleManager] JUMP_PADS Enabled
[20:22:26 INFO]: HubBasics Debug >> [ModuleManager] ADVANCED_MOTD Enabled
[20:22:26 INFO]: HubBasics Debug >> [ModuleManager] CONNECTION_MESSAGES Enabled
[20:22:26 INFO]: HubBasics Debug >> [ModuleManager] BOSSBAR_MESSAGES Enabled
[20:22:26 INFO]: HubBasics Debug >> [ModuleManager] DOUBLE_JUMP Enabled
[20:22:26 INFO]: HubBasics Debug >> [ModuleManager] ANTI_VOID Enabled
[20:22:26 INFO]: HubBasics Debug >> [ModuleManager] FIXED_WEATHER Enabled
[20:22:26 INFO]: HubBasics Debug >> [ModuleManager] AUTOMATED_BROADCASTS Enabled
```

**Closed by Fabricio20** 2016-07-06 23:23 UTC
Labels: Bug, Duplicate

**Comment by blakefmc** [comment] 2016-07-06 23:31
What about the latest build?

**Comment by Fabricio20** [comment] 2016-07-06 23:34
Build 40, by the time I'm writing, is the latest build. http://jenkins.notfab.net/job/HubBasics/40/

**Comment by blakefmc** [comment] 2016-07-06 23:37
Ah, thanks it works! your the best :)

**Comment by wobkobi** [comment] 2022-06-03 08:56
epic thanks :)

**Comment by wobkobi** [comment] 2022-06-03 08:56
epic thank you so much :))
